### ISSUE TITLE
Use API for Own Dataset

### ISSUE THREAD

**Issue by jessxphil** [yuanqidu/GraphGT#1]
Hi @yuanqidu! 

Love your work! The area of graph generation is of special interest to me as well. Specially, fixed-sized generation for skeleton datasets. I have a quick question. I have my own skeleton graph dataset, that I would like to use for the graph generation task, do you have a quick summation of how I would go about doing that? 

Thank you in advance! I'm sure you're plenty busy!

Jess

**Comment by yuanqidu** [comment]
Thanks for your interest and sorry about the late response.

Definitely, as we mostly provide datasets in its ready-to-use format, this repo does not have the code to process a raw dataset. 

My suggestion is to decompose the data by its node feature, edge feature, adjencency matrix, spatial feature, etc. and store them in individual files.

We also welcome contributions from the community, if you'd like to contribute the dataset to our server, we would also be grateful to work with you through it and prepare the ready-to-use version!

Happy new year!
