### ISSUE TITLE
Questions about using graphGT in the model

### ISSUE THREAD

**Issue by RENEK-bool** [yuanqidu/GraphGT#4]
Hello, thank you very much for your work. I just started to learn graph generation technology, and I noticed that there are graphvae models in the code, but I looked carefully and didn't seem to have any connection with GraphGT. I've downloaded the n_body_charged dataset. But I found that the code also needs a file like train.dat, which seems to require further data processing on the dataset. Could you give me some guidance on how to further apply GraphGT in graphvae？

**Comment by yuanqidu** [comment]
Thanks for your interest! The dataset we provide is for general-purpose where we store in numpy, if you would like to run graphvae code (where we took from [graphrnn](https://github.com/JiaxuanYou/graph-generation) github repo), you need to convert the dataset to .dat required by the code.

**Comment by RENEK-bool** [comment]
Thank you for your timely response and I look forward to graphGT's further improvement and dataset enrichment！

**Comment by ws0905** [comment]
Hello, thank you very much for your work. I have downloaded the brain networks dataset, but I found some problems: 1. FC in the dataset_ concatenated_ adj、SC_ concatenated_ The data in adj is all 0, which seems unreasonable. 2、FC_ concatenated_ edge_ feat、SC_ concatenated_ edge_ What the fourth dimension of feat stands for is missing. 3. There is no explanation for selecting 68 ROIs. These problems have brought me some difficulties in using the data set. Can you help me? Thank you.
